### ISSUE TITLE
Problems running your code

### ISSUE THREAD

**Issue by chapmanbe** [rutgervandeleur/uncertainty#3]
I'm trying to run your code and am having some difficulties. I was hoping you could clarify some issues for me.

In your repository I could not see what version of python you used. I'm using Python 3.7.

When I run

`python main.py --epistemic_method varinf --aleatoric_method bayesdecomp`

I get a pickling error due to the lambda function in the `__init__` method in the `BayesBasicBlock` class. Replacing the lambda function with a proper function resolves that problem.

However, I then get a `KeyError`:

```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jupyter/uncertainty/uncertainty/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jupyter/uncertainty/uncertainty/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jupyter/uncertainty/uncertainty/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jupyter/uncertainty/uncertainty/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jupyter/uncertainty/project/utils/dataloader.py", line 141, in __getitem__
    id = self.path_labels['id'].iloc[idx]
  File "/home/jupyter/uncertainty/uncertainty/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/jupyter/uncertainty/uncertainty/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'id'
```
Any idea what is going on here? I'm wondering if the data formats have changed.

When I download the CPSC2018 validation set my filename is different than what you have in your config file. Namely

- You have: CPSC2018_REFERENCES.csv
- I have: REFERENCE.csv

The file has four columns:  Recording | First_label | Second_label | Third_label

Want to make sure this is the same as you.

**Comment by JeroenVranken** [comment]
Hi Brian,

> In your repository I could not see what version of python you used. I'm using Python 3.7.

We used Python 3.7 for this project.


> I get a pickling error due to the lambda function in the __init__ method in the BayesBasicBlock class. Replacing the lambda function with a proper function resolves that problem.

I personally never had issues with pickling the lambda function, but it seems like you have resolved this issue?

**Regarding the data loading:**
You are correct, the file I used is indeed different. I currently don't have access to all the files, but thankfully it is only a small change. The dataloader does not support the `A0001` format of the original `REFERENCES.csv`, but looks for a column called `id`. This column is simply an incrementing integer, the same as the `Recording` column with `A000` stripped off.

I just pushed the correct file for the validation set (`CPSC2018_REFERENCES.csv`) to the repository, which can be found [here](https://github.com/rutgervandeleur/uncertainty/blob/master/project/data/CPSC2018/validation_set/CPSC2018_REFERENCES.csv).

For the other sets (train, test), you can simply modify the `REFERENCES.csv` file to contain an additional column with incremental id. For example using pandas:
```python
import pandas as pd

df = pd.read_csv('REFERENCES.csv')
df['id'] = df.index + 1

pd.to_csv('CPSC2018_REFERENCES.csv')
```

Please let me know if this solves the issue.

**Comment by chapmanbe** [comment]
Yes. Your tip resolved the problem. Sorry I didn't debug that on my own, but it was really deep in the call stack without the best interface on GCP for me to dig through the problem.

**Comment by JeroenVranken** [comment]
Great! Glad I could be of help. Please let me know if you run into any other issues.

I edited the `README.MD` to include these instructions, so future users of the repository will use the correct file.
